spring:
  datasource:
    url: jdbc:mysql://12.57.78.16:3306/dream?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    username: hw3
    password:


