spring:
  datasource:
    url: jdbc:mysql://1.57.78.16:3306/111?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    username: hw3
    password: 


