spring:
  datasource:
    url: jdbc:mysql://123.57.78.161:3306/dream?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    username: hw3
    password: Y8CVZTCbjqRYG#


